const Task = require('../models/Task');

// @desc    Chat with Gemini about tasks
// @route   POST /api/ai/chat
// @access  Public
exports.chatWithAI = async (req, res) => {
  try {
    const { message, history } = req.body;

    if (!message || message.trim() === '') {
      return res.status(400).json({ message: 'User message is required' });
    }

    // 1. Retrieve logged-in user's tasks from database to build the AI's context
    const tasks = await Task.find({ user: req.user._id }).sort({ dueDate: 1, createdAt: -1 });

    const formattedTasks = tasks.map(t => {
      const status = t.completed ? 'Completed' : 'Pending';
      const due = t.dueDate ? new Date(t.dueDate).toLocaleDateString() : 'No due date';
      const desc = t.description ? ` - Desc: ${t.description}` : '';
      return `- [${status}] Title: "${t.title}" | Priority: ${t.priority} | Due: ${due}${desc} (ID: ${t._id})`;
    }).join('\n');

    // 2. Formulate system instruction prompt
    const systemPrompt = `You are "TaskSphere AI Assistant", a premium productivity coach and workspace assistant.
You help the user analyze, summarize, and understand their task list.

Below is the complete list of tasks in the user's workspace:
${tasks.length === 0 ? "No tasks exist in the workspace currently." : formattedTasks}

Guidelines:
1. ONLY talk about tasks. Do not attempt to create, edit, or delete tasks.
2. If the user asks you to perform an action (e.g. "Add a task to buy groceries" or "Mark the code review task as complete"), politely respond that you can only talk about/analyze their tasks, but they can perform those actions directly on the dashboard using the controls.
3. Keep answers highly professional, neat, and well-structured using markdown formatting (bullet points, bold text).
4. Guide the conversation back to productivity and tasks if the user asks off-topic or general knowledge questions.`;

    // 3. Map history to Gemini's format
    const contents = [];
    if (history && Array.isArray(history)) {
      history.forEach(item => {
        contents.push({
          role: item.role === 'user' ? 'user' : 'model',
          parts: [{ text: item.text }]
        });
      });
    }
    
    // Add current user query
    contents.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ message: 'GEMINI_API_KEY is not configured on the server' });
    }

    // 4. Send request to Gemini API
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          systemInstruction: {
            parts: [{ text: systemPrompt }]
          },
          contents: contents
        })
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      console.error(`Gemini API Error: ${errText}`);
      return res.status(response.status).json({
        message: 'Failed to communicate with AI service',
        error: errText
      });
    }

    const data = await response.json();
    
    if (!data.candidates || data.candidates.length === 0) {
      return res.status(500).json({ message: 'No response candidates generated by AI model' });
    }

    const aiReply = data.candidates[0].content.parts[0].text;

    res.status(200).json({
      response: aiReply
    });

  } catch (error) {
    console.error(`Error in AI Controller: ${error.message}`);
    res.status(500).json({ message: 'Error processing AI chat query', error: error.message });
  }
};
